development: &development
  ws_url: "http://localhost:3000"
  ps_url: "http://localhost:3000"
  return_to: "http://localhost:3000/obrigado"
  email: hi@joaonetto.me
  token: "tokenGeradoPeloPagseguro"

test:
  <<: *development

production:
  ws_url: "https://ws.pagseguro.uol.com.br"
  ps_url: "https://pagseguro.uol.com.br"
  return_to: "http://prc25anos.herokuapp.com/obrigado"
  email: hi@joaonetto.ms
  token: "tokenGeradoPeloPagseguro"