development: &development
  ws_url: "https://ws.pagseguro.uol.com.br"
  ps_url: "https://pagseguro.uol.com.br"
  return_to: "http://prc25anos.herokuapp.com/obrigado"
  email: hi@joaonetto.me
  token: "ABBDBF3012E5491794C55810002C491A"

test:
  <<: *development

production:
  ws_url: "https://ws.pagseguro.uol.com.br"
  ps_url: "https://pagseguro.uol.com.br"
  return_to: "http://prc25anos.herokuapp.com/obrigado"
  email: hi@joaonetto.ms
  token: "ABBDBF3012E5491794C55810002C491A"