development: &development
  ws_url: "https://ws.pagseguro.uol.com.br"
  ps_url: "https://pagseguro.uol.com.br"
  return_to: "http://prc25anos.herokuapp.com/obrigado"
  email: dionei.ochner@gmail.com
  token: "8166C981DA664E49B02BE6EE61C87DD9"

test:
  <<: *development

production:
  ws_url: "https://ws.pagseguro.uol.com.br"
  ps_url: "https://pagseguro.uol.com.br"
  return_to: "http://prc25anos.herokuapp.com/obrigado"
  email: dionei.ochner@gmail.com
  token: "8166C981DA664E49B02BE6EE61C87DD9"